### ISSUE TITLE
Provide Kubernetes Statefulset deployment files on AWS graviton

### ISSUE THREAD

**Issue by RajaPoseidon** [voltrondata/SQLFlite#38]
Hi , As mentioned in the demo  can you also provide Kubernetes  stateful set deployment files

**Comment by RajaPoseidon** [comment]
@prmoore77 when you get a chance can you please commit the statefulset deployment files ?

**Comment by prmoore77** [comment]
Hi @RajaPoseidon - we have an internal helm chart, but it is tailored to a specific EKS environment at present.  I'll try to make it more generic and put it in this repo relatively soon.  Thanks.
